# Generated by Django 5.2.11 on 2026-06-19 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('BTECH', 'B.Tech'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MTECH', 'M.Tech'), ('OTHER', 'Others')], max_length=20)),
                ('semester', models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=2)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
